---
- name:
  hosts: all
  tasks:
       - name: create /etc/myhost file in dev host
         template:
                 src: host.j2
                 dest: /etc/myhost
         when: "'dev' in group_names"


...
